stages:
  - test

test:
  stage: test
  tags:
    - junit
    - test
    - report
  script:
    - mvn clean test
  artifacts:
    when: always
    paths:
      - target/surefire-reports/*.xml
    reports:
      junit: target/surefire-reports/*.xml
